---
- name: Deploy Nexus Repository Manager
  hosts: servers
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create a volume for Nexus data
      command: docker volume create nexus-data

    - name: Run Nexus container
      docker_container:
        name: nexus
        image: sonatype/nexus3
        state: present
        ports:
          - "8081:8081"
        volumes:
          - nexus-data:/nexus-data
        restart_policy: unless-stopped

    - name: Wait for Nexus to be ready
      uri:
        url: http://localhost:8081
        return_content: yes
        status_code: 200
      register: result
      until: result is not failed
      retries: 10
      delay: 10
