---
- name: Deploy Nexus Repository Manager
  hosts: servers
  become: yes
  tasks:

    - name: Create a volume for Nexus data
      command: docker volume create nexus-data

    - name: Run Nexus container
      docker_container:
        name: nexus
        image: sonatype/nexus3
        state: present
        ports:
          - "8081:8081"
        volumes:
          - nexus-data:/nexus-data
        restart_policy: unless-stopped

    - name: Wait for Nexus to be ready
      uri:
        url: http://localhost:8081
        return_content: yes
        status_code: 200
      register: result
      until: result is not failed
      retries: 10
      delay: 10
