- hosts: servers
  become: yes
  vars:
    run_dir: "/opt/java_run/simple_xml_parser"
    java_repo_url: "https://github.com/romanborodin1/java.git"

  tasks:
    - name: Install Java JDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Ensure the parent directory exists
      file:
        path: "/opt/java_run"
        state: directory
        
    - name: Remove existing simple_xml_parser directory if it exists
      file:
        path: "{{ run_dir }}"
        state: absent

    - name: Clone the Java application repository
      git:
        repo: "{{ java_repo_url }}"  # URL репозитория с Java приложением
        dest: "{{ run_dir }}"
        version: main

    - name: Compile the Java application
      shell: |
        cd {{ run_dir }} && javac ReadXmlDomParser.java
      args:
        chdir: "{{ run_dir }}"

    - name: Run the Java application
      shell: |
        cd {{ run_dir }} && java -cp . ReadXmlDomParser resources/wf.xml
      args:
        chdir: "{{ run_dir }}"
