- hosts: servers
  become: yes
  vars:
    run_dir: "/opt/java_run/simple_xml_parser"  # Директория для работы

  tasks:
    - name: Install Java JDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Recreate the run directory
      file:
        path: "{{ run_dir }}"
        state: directory

    - name: Clone the Java application repository
      git:
        repo: "{{ java_repo_url }}"  # URL репозитория с Java приложением
        dest: "{{ run_dir }}"
        version: main

    - name: Check if Java file exists
      stat:
        path: "{{ run_dir }}/ReadXmlDomParser.java"
      register: java_file

    - name: Fail if Java file does not exist
      fail:
        msg: "Java file not found: {{ run_dir }}/ReadXmlDomParser.java"
      when: not java_file.stat.exists

    - name: Compile the Java application
      shell: |
        javac -d . ReadXmlDomParser.java
      args:
        chdir: "{{ run_dir }}"

    - name: Check if compiled class exists
      stat:
        path: "{{ run_dir }}/ReadXmlDomParser.class"
      register: class_file

    - name: Fail if compiled class does not exist
      fail:
        msg: "Compiled class not found!"
      when: not class_file.stat.exists

    - name: Run the Java application
      shell: |
        java -cp . ReadXmlDomParser wf.xml
      args:
        chdir: "{{ run_dir }}"
