- hosts: servers
  become: yes
  vars:
    java_repo_url: "{{ java_repo_url }}"  # URL репозитория с Java приложением
    run_dir: "/opt/java_run"  # Директория для запуска

  tasks:
    - name: Install Java JDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create run directory
      file:
        path: "{{ run_dir }}"
        state: directory

    - name: Clone the Java application repository
      git:
        repo: "{{ java_repo_url }}"
        dest: "{{ run_dir }}"
        version: main

    - name: Compile the Java application
      shell: |
        cd {{ run_dir }} && javac -d . ReadXmlDomParser.java
      args:
        chdir: "{{ run_dir }}"

    - name: Check if compiled class exists
      stat:
        path: "{{ run_dir }}/simple_xml_parser/ReadXmlDomParser.class"
      register: class_file

    - name: Fail if compiled class does not exist
      fail:
        msg: "Compiled class not found!"
      when: not class_file.stat.exists

    - name: Run the Java application
      shell: |
        java -cp {{ run_dir }} ReadXmlDomParser resources/wf.xml
      args:
        chdir: "{{ run_dir }}"
