- hosts: servers
  become: yes
  vars:
    java_repo_url: "{{ java_repo_url }}"  # URL репозитория с Java приложением
    java_repo_name: "{{ java_repo_url | basename | regex_replace('\\.git$', '') }}"  # Извлечение имени репозитория
    run_dir: "/opt/{{ java_repo_name }}_run"  # Директория для запуска

  tasks:
    - name: Install Java JDK
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create run directory
      file:
        path: "{{ run_dir }}"
        state: directory

    - name: Clone the Java application repository
      git:
        repo: "{{ java_repo_url }}"
        dest: "{{ run_dir }}"
        version: main

    - name: Compile the Java application
      shell: |
        javac simple_xml_parser/ReadXmlDomParser.java
      args:
        chdir: "{{ run_dir }}"

    - name: Run the Java application
      shell: |
        java -cp "{{ run_dir }}" simple_xml_parser.ReadXmlDomParser
      args:
        chdir: "{{ run_dir }}"
